version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/example
      - IMAGE=$REPO:latest
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $IMAGE .
      - echo "Pushing the Docker image to ECR..."
      - docker push $IMAGE
  post_build:
    commands:
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"example","imageUri":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
  files: imagedefinitions.json